# Generated by Django 4.1.7 on 2023-02-21 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='id пользователя')),
                ('bio', models.TextField(blank=True, verbose_name='описание пользователя')),
                ('profile_image', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images', verbose_name='аватар пользователя')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='адрес пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
